spring:
  cloud:
    function:
      definition: dusense
    stream:
      binder:
        redis:
          default:
            backOffInitialInterval: 1000
            backOffMaxInterval: 10000
            backOffMultiplier: 2.0
            concurrency: 1
            maxAttempts: 3
      default-binder: redis
      bindings:
        dusense-in-0: # 输入通道名称
          destination: dusense  # 输入目的地名称
      redis:
        binder:
          type: redis  # 指定使用 Redis Binder
          environment: myRedisEnvironment  # 指定 Redis 环境的名称
          brokers: 10.10.14.168:6371,10.10.14.168:6372,10.10.14.168:6373  # Redis 服务器地址
          password: 1234  # Redis 密码
          database: 0  # Redis 数据库编号
          cluster:
            nodes: 10.10.14.168:6371,10.10.14.168:6372,10.10.14.168:6373  # Redis Cluster 节点地址